In [53]:
import numpy as np

In [6]:
# 1 D Array 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# 2 D Array 
b = np.array([
    [3.0,4.0,5.0],
    [6.0,7.0,8.0]
])
print(b)

[[3. 4. 5.]
 [6. 7. 8.]]


In [8]:
# Get Dimensions
b.ndim

2

In [9]:
# Get Shape (rows &colums)
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int64')

In [11]:
# Get Size
b.itemsize

8

In [12]:
# Arrays manipulations
c = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
# Getting specific Elements [r,c]
number8 = c[1,2]
print(number8)

8


In [14]:
# Getting a specific row [row_index, :]
row1 = c[1, :]
row0 = c[0, :]
print(row1)
print(row0)

[ 6  7  8  9 10]
[1 2 3 4 5]


In [15]:
# Getting a spefic column [:, column_index]
column1 = c[:, 2]
print(column1)

[3 8]


In [16]:
#initializing types of Arrays
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#All 1s matrix
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [19]:
#Random decimal numbers
np.random.rand(4,1)

array([[0.75901505],
       [0.69844775],
       [0.43122164],
       [0.37838056]])

In [21]:
# Random Integer numbers
np.random.randint(7,size=(3,3))

array([[3, 1, 0],
       [6, 5, 3],
       [3, 0, 5]])

In [22]:
# Exercise 
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
# Copying Array
a = np.array([2,3,4])
b = a
print(b) -- defect

[2 3 4]


In [26]:
# Copying Array
a = np.array([2,3,4])
b = a.copy()
b[1] = 100
print(b) -- correct

[  2 100   4]


In [29]:
# Mathematics in NumPy
a = np.array([2,3,4])
print(a)

[2 3 4]


In [30]:
# Addition
a + 2

array([4, 5, 6])

In [31]:
# Subtraction
a - 2

array([0, 1, 2])

In [32]:
# Division
a / 2

array([1. , 1.5, 2. ])

In [33]:
# Multiplication 
a * 2

array([4, 6, 8])

In [35]:
# Statistics 
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a)

[[1 2 3]
 [4 5 6]]


In [39]:
# Min Value
print(np.min(a))

1


In [40]:
# Max Value
print(np.max(a))

6


In [42]:
# Minimum along axis 1 (row-wise)
print(np.min(a, axis = 1 ))

[1 4]


In [43]:
# Maxmun along axis 1 (row-wise)
print(np.max(a, axis = 1))

[3 6]


In [44]:
# Sum
sum = np.sum(a)
print(sum)

21


In [46]:
# Mean
mean = np.mean(a)
print(mean)

3.5


In [51]:
# Vertical stacking (vstacks)
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

stack = np.vstack([v1, v2])
print(stack)

[[1 2 3]
 [4 5 6]]


In [52]:
# Horizontal Stacking (Hstacks)
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

stack = np.hstack((v1, v2))
print(stack)

[1 2 3 4 5 6]
